// The tsconfig file has a bunch of options that you can change to change the compilation process.
// Some of these include

// The tsconfig file has a bunch of options that you can change to change the compilation process.
// Some of these include

const greet = (name: string) => `Hello, ${name}!`;

// important point:-
// We don't push .js file in github because it is auto generated by typscript file.
// To fix this we put or generate all the .js file in one folder than we put this
// folder on .gitignore.

/*
"rootDir": "./src", // contain all the typescript file
"outDir": "./dist", // here file name can be 'dist' or 'build'
----> This will help us make structure folder structure.
*/
